name: Deploy to Development Environment

on:
  push:
    branches:
      - dev  # Trigger on push to the dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      S3_BUCKET: my-app-dev  # Your S3 bucket name for the dev environment
      CLOUDFRONT_DIST_ID: ${{ secrets.CLOUDFRONT_DEV_DIST_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Sync S3 Bucket for Dev
      run: |
        aws s3 sync ./dev s3://$S3_BUCKET --delete --region $AWS_REGION

    - name: Invalidate CloudFront Cache for Dev
      run: |
        aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
