name: Test GitHub Actions Workflow

on:
  push:
    branches:
      - feature  # Trigger on push to 'feature' branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print a message
      run: echo "The workflow is running successfully!"

    - name: Verify AWS CLI Version
      run: aws --version
