name: Deploy to pre-pod Environment

on:
  push:
    branches:
      - feature 
    paths:
      - pre-pod/** # This triggers the workflow for any changes in the pre-pod folder

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      S3_BUCKET: myfirstbucket509123001245 # Your S3 bucket name for the pre-pod environment
      CLOUDFRONT_DIST_ID: ${{ secrets.CLOUDFRONT_DEV_DIST_ID }} # Ensure this is set correctly

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
   
    - name: Deploy to S3
      run: |
        aws s3 cp pre-pod/index.html s3://${{ env.S3_BUCKET }}/index.html3
         
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*"
